title: "Ab Aeterno"
logo: /assets/img/map.png
description: The 8Follies map & notes
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
include: ["_posts"]
github:
  is_project_page: true
  repository_nwo: "Grimmhaus & 8Follies notes"
  repository_url: "https://github.com/h-griffin/dnd-notes"
  owner_url: "https://github.com/h-griffin"