title: "Ab Aeterno"
logo: "/assets/img/Ab_Aeterno_World_Map.png"
sub_logo: "/assets/img/The_Far_Island.png"
description: >-
  <p>Cartographer Lore Records</p> <ul><li> <a href='https://h-griffin.github.io/dnd-notes/_posts'>All Posts </a> </li><li><a href='https://h-griffin.github.io/dnd-notes/_posts/chapters'>All Chapters</a> </li><li> <a href='https://h-griffin.github.io/dnd-notes/_posts/chapter-11'>Current [Chapter 11]</a> </li></ul>
show_downloads: false
theme: jekyll-theme-minimal
include:
  - "_posts"
github:
  is_project_page: true
  repository_nwo: "Ab Aeterno notes"
  repository_url: "https://github.com/h-griffin/dnd-notes"
  owner_url: "https://github.com/h-griffin" 