title: "Ab Aeterno map"
logo: /assets/img/map.png
description: The 8Follies Grimmhaus notes
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: true
  repository_nwo: "Ab Aeterno: Grimmhaus notes"
  repository_url: "https://github.com/h-griffin/dnd-notes"
  owner_url: "https://github.com/h-griffin"